---
- name: "Include variables for Debian platform"
  include_vars: Debian.yml
  when: ansible_distribution == "Debian"

- name: "Include variables for Ubuntu platform"
  include_vars: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: "Install xfce4 packages"
  package:
    name: "{{ xfce4_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 86400

- name: "Install login manager packages"
  package:
    name: "{{ xfce4_login_manager_package }}"
    state: present
  notify: "Restart login manager service"

- name: "Install xfce4 extra packages"
  package:
    name: "{{ xfce4_extra_packages }}"
    state: present
